
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.travelport.service.system_v8_0;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-04-08T10:54:07.687-06:00
 * Generated source version: 2.7.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "ExternalCacheAccessService",
                      portName = "ExternalCacheAccessPort",
                      targetNamespace = "http://www.travelport.com/service/system_v8_0",
                      wsdlLocation = "file:/C:/Travelport/SamplesAutoMation/AutoWork/travelport-uapi-tutorial/wsdl/system_v8_0/System.wsdl",
                      endpointInterface = "com.travelport.service.system_v8_0.ExternalCacheAccessPortType")
                      
public class ExternalCacheAccessPortTypeImpl implements ExternalCacheAccessPortType {

    private static final Logger LOG = Logger.getLogger(ExternalCacheAccessPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.travelport.service.system_v8_0.ExternalCacheAccessPortType#service(com.travelport.schema.system_v8_0.ExternalCacheAccessReq  parameters )*
     */
    public com.travelport.schema.system_v8_0.ExternalCacheAccessRsp service(com.travelport.schema.system_v8_0.ExternalCacheAccessReq parameters) throws SystemFaultMessage    { 
        LOG.info("Executing operation service");
        System.out.println(parameters);
        try {
            com.travelport.schema.system_v8_0.ExternalCacheAccessRsp _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SystemFaultMessage("SystemFaultMessage...");
    }

}
