package com.travelport.service.vehicle_v42_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2017-07-31T15:56:34.217-06:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://www.travelport.com/service/vehicle_v42_0", name = "VehicleSearchServicePortType")
@XmlSeeAlso({com.travelport.schema.common_v42_0.ObjectFactory.class, com.travelport.schema.vehicle_v42_0.ObjectFactory.class, com.travelport.soa.common.security.sessioncontext_v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface VehicleSearchServicePortType {

    @WebResult(name = "VehicleSearchAvailabilityRsp", targetNamespace = "http://www.travelport.com/schema/vehicle_v42_0", partName = "result")
    @WebMethod(action = "http://localhost:8080/kestrel/VehicleService")
    public com.travelport.schema.vehicle_v42_0.VehicleSearchAvailabilityRsp service(
        @WebParam(partName = "parameters", name = "VehicleSearchAvailabilityReq", targetNamespace = "http://www.travelport.com/schema/vehicle_v42_0")
        com.travelport.schema.vehicle_v42_0.VehicleSearchAvailabilityReq parameters
    ) throws VehicleFaultMessage;
}
