
package com.travelport.service.vehicle_v26_0;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-04-08T10:54:46.701-06:00
 * Generated source version: 2.7.10
 * 
 */
public final class VehicleRulesServicePortType_VehicleRulesServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.travelport.com/service/vehicle_v26_0", "VehicleService");

    private VehicleRulesServicePortType_VehicleRulesServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = VehicleService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        VehicleService ss = new VehicleService(wsdlURL, SERVICE_NAME);
        VehicleRulesServicePortType port = ss.getVehicleRulesServicePort();  
        
        {
        System.out.println("Invoking service...");
        com.travelport.schema.vehicle_v26_0.VehicleRulesReq _service_parameters = null;
        try {
            com.travelport.schema.vehicle_v26_0.VehicleRulesRsp _service__return = port.service(_service_parameters);
            System.out.println("service.result=" + _service__return);

        } catch (VehicleFaultMessage e) { 
            System.out.println("Expected exception: VehicleFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
