
package com.travelport.service.system_v32_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.5
 * 2017-07-31T15:54:47.889-06:00
 * Generated source version: 3.1.5
 */

@WebFault(name = "ErrorInfo", targetNamespace = "http://www.travelport.com/schema/common_v32_0")
public class SystemFaultMessage extends Exception {
    
    private com.travelport.schema.common_v32_0.ErrorInfo errorInfo;

    public SystemFaultMessage() {
        super();
    }
    
    public SystemFaultMessage(String message) {
        super(message);
    }
    
    public SystemFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public SystemFaultMessage(String message, com.travelport.schema.common_v32_0.ErrorInfo errorInfo) {
        super(message);
        this.errorInfo = errorInfo;
    }

    public SystemFaultMessage(String message, com.travelport.schema.common_v32_0.ErrorInfo errorInfo, Throwable cause) {
        super(message, cause);
        this.errorInfo = errorInfo;
    }

    public com.travelport.schema.common_v32_0.ErrorInfo getFaultInfo() {
        return this.errorInfo;
    }
}
