package com.travelport.service.air_v26_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-04-08T10:46:28.899-06:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://www.travelport.com/service/air_v26_0", name = "AirTicketingPortType")
@XmlSeeAlso({com.travelport.schema.rail_v26_0.ObjectFactory.class, com.travelport.schema.common_v26_0.ObjectFactory.class, com.travelport.schema.air_v26_0.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AirTicketingPortType {

    @WebResult(name = "AirTicketingRsp", targetNamespace = "http://www.travelport.com/schema/air_v26_0", partName = "result")
    @WebMethod(action = "http://localhost:8080/kestrel/AirService")
    public com.travelport.schema.air_v26_0.AirTicketingRsp service(
        @WebParam(partName = "parameters", name = "AirTicketingReq", targetNamespace = "http://www.travelport.com/schema/air_v26_0")
        com.travelport.schema.air_v26_0.AirTicketingReq parameters
    ) throws AirFaultMessage;
}
