
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.travelport.service.hotel_v35_0;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-03-09T16:22:43.717-07:00
 * Generated source version: 3.1.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "HotelService",
                      portName = "HotelUpsellSearchServicePort",
                      targetNamespace = "http://www.travelport.com/service/hotel_v35_0",
                      wsdlLocation = "file:/C:/Travelport_1/SamplesAutoMation/AutoWork/travelport-uapi-tutorial-v35/Wsdl/hotel_v35_0/Hotel.wsdl",
                      endpointInterface = "com.travelport.service.hotel_v35_0.HotelUpsellSearchServicePortType")
                      
public class HotelUpsellSearchServicePortImpl implements HotelUpsellSearchServicePortType {

    private static final Logger LOG = Logger.getLogger(HotelUpsellSearchServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.travelport.service.hotel_v35_0.HotelUpsellSearchServicePortType#service(com.travelport.schema.hotel_v35_0.HotelUpsellDetailsReq  parameters )*
     */
    public com.travelport.schema.hotel_v35_0.HotelUpsellDetailsRsp service(com.travelport.schema.hotel_v35_0.HotelUpsellDetailsReq parameters) throws HotelFaultMessage    { 
        LOG.info("Executing operation service");
        System.out.println(parameters);
        try {
            com.travelport.schema.hotel_v35_0.HotelUpsellDetailsRsp _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new HotelFaultMessage("HotelFaultMessage...");
    }

}
