
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.travelport.service.hotel_v17_0;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-05-05T13:55:28.574+02:00
 * Generated source version: 2.6.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "HotelService",
                      portName = "HotelSearchServicePort",
                      targetNamespace = "http://www.travelport.com/service/hotel_v17_0",
                      wsdlLocation = "http://localhost:8080/kestrel/HotelService?wsdl",
                      endpointInterface = "com.travelport.service.hotel_v17_0.HotelSearchServicePortType")
                      
public class HotelSearchServicePortTypeImpl implements HotelSearchServicePortType {

    private static final Logger LOG = Logger.getLogger(HotelSearchServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.travelport.service.hotel_v17_0.HotelSearchServicePortType#service(com.travelport.schema.hotel_v17_0.HotelSearchAvailabilityReq  parameters )*
     */
    public com.travelport.schema.hotel_v17_0.HotelSearchAvailabilityRsp service(com.travelport.schema.hotel_v17_0.HotelSearchAvailabilityReq parameters) throws HotelFaultMessage    { 
        LOG.info("Executing operation service");
        System.out.println(parameters);
        try {
            com.travelport.schema.hotel_v17_0.HotelSearchAvailabilityRsp _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new HotelFaultMessage("HotelFaultMessage...");
    }

}
