package com.travelport.service.system_v8_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-04-23T19:15:28.137+02:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://www.travelport.com/service/system_v8_0", name = "SystemTimePortType")
@XmlSeeAlso({com.travelport.schema.system_v8_0.ObjectFactory.class, com.travelport.schema.common_v12_0.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SystemTimePortType {

    @WebResult(name = "TimeRsp", targetNamespace = "http://www.travelport.com/schema/system_v8_0", partName = "result")
    @WebMethod(action = "http://localhost:8080/kestrel/SystemService")
    public com.travelport.schema.system_v8_0.TimeRsp service(
        @WebParam(partName = "parameters", name = "TimeReq", targetNamespace = "http://www.travelport.com/schema/system_v8_0")
        com.travelport.schema.system_v8_0.TimeReq parameters
    ) throws SystemFaultMessage;
}
