
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.travelport.service.system_v8_0;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-04-23T19:15:28.114+02:00
 * Generated source version: 2.6.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "SystemService",
                      portName = "SystemPingPort",
                      targetNamespace = "http://www.travelport.com/service/system_v8_0",
                      wsdlLocation = "http://localhost:8080/kestrel/ExternalCacheAccessService?wsdl",
                      endpointInterface = "com.travelport.service.system_v8_0.SystemPingPortType")
                      
public class SystemPingPortTypeImpl implements SystemPingPortType {

    private static final Logger LOG = Logger.getLogger(SystemPingPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.travelport.service.system_v8_0.SystemPingPortType#service(com.travelport.schema.system_v8_0.PingReq  parameters )*
     */
    public com.travelport.schema.system_v8_0.PingRsp service(com.travelport.schema.system_v8_0.PingReq parameters) throws SystemFaultMessage    { 
        LOG.info("Executing operation service");
        System.out.println(parameters);
        try {
            com.travelport.schema.system_v8_0.PingRsp _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SystemFaultMessage("SystemFaultMessage...");
    }

}
