package com.travelport.service.vehicle_v38_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-09-13T11:40:17.867-06:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://www.travelport.com/service/vehicle_v38_0", name = "VehicleLocationDetailServicePortType")
@XmlSeeAlso({com.travelport.schema.common_v38_0.ObjectFactory.class, com.travelport.schema.vehicle_v38_0.ObjectFactory.class, com.travelport.soa.common.security.sessioncontext_v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface VehicleLocationDetailServicePortType {

    @WebResult(name = "VehicleLocationDetailRsp", targetNamespace = "http://www.travelport.com/schema/vehicle_v38_0", partName = "result")
    @WebMethod(action = "http://localhost:8080/kestrel/VehicleService")
    public com.travelport.schema.vehicle_v38_0.VehicleLocationDetailRsp service(
        @WebParam(partName = "parameters", name = "VehicleLocationDetailReq", targetNamespace = "http://www.travelport.com/schema/vehicle_v38_0")
        com.travelport.schema.vehicle_v38_0.VehicleLocationDetailReq parameters,
        @WebParam(partName = "sessionContext", name = "SessionContext", targetNamespace = "http://www.travelport.com/soa/common/security/SessionContext_v1", header = true)
        com.travelport.soa.common.security.sessioncontext_v1.SessionContext sessionContext
    ) throws VehicleFaultMessage;
}
