package com.travelport.service.air_v42_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2017-07-31T15:51:35.904-06:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://www.travelport.com/service/air_v42_0", name = "FlightInfoPortType")
@XmlSeeAlso({com.travelport.schema.common_v42_0.ObjectFactory.class, com.travelport.schema.air_v42_0.ObjectFactory.class, com.travelport.schema.rail_v42_0.ObjectFactory.class, com.travelport.soa.common.security.sessioncontext_v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FlightInfoPortType {

    @WebResult(name = "FlightInformationRsp", targetNamespace = "http://www.travelport.com/schema/air_v42_0", partName = "result")
    @WebMethod(action = "http://localhost:8080/kestrel/FlightService")
    public com.travelport.schema.air_v42_0.FlightInformationRsp service(
        @WebParam(partName = "parameters", name = "FlightInformationReq", targetNamespace = "http://www.travelport.com/schema/air_v42_0")
        com.travelport.schema.air_v42_0.FlightInformationReq parameters
    ) throws AirFaultMessage;
}
