
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.travelport.service.vehicle_v17_0;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-05-05T19:47:19.509+02:00
 * Generated source version: 2.6.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "VehicleService",
                      portName = "VehicleRetrieveServicePort",
                      targetNamespace = "http://www.travelport.com/service/vehicle_v17_0",
                      wsdlLocation = "http://localhost:8080/kestrel/VehicleService?wsdl",
                      endpointInterface = "com.travelport.service.vehicle_v17_0.VehicleRetrieveServicePortType")
                      
public class VehicleRetrieveServicePortTypeImpl implements VehicleRetrieveServicePortType {

    private static final Logger LOG = Logger.getLogger(VehicleRetrieveServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.travelport.service.vehicle_v17_0.VehicleRetrieveServicePortType#service(com.travelport.schema.vehicle_v17_0.VehicleRetrieveReq  parameters )*
     */
    public com.travelport.schema.vehicle_v17_0.VehicleRetrieveRsp service(com.travelport.schema.vehicle_v17_0.VehicleRetrieveReq parameters) throws VehicleFaultMessage    { 
        LOG.info("Executing operation service");
        System.out.println(parameters);
        try {
            com.travelport.schema.vehicle_v17_0.VehicleRetrieveRsp _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new VehicleFaultMessage("VehicleFaultMessage...");
    }

}
