package com.travelport.service.system_v9_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-19T15:09:22.867-06:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://www.travelport.com/service/system_v9_0", name = "SystemInfoPortType")
@XmlSeeAlso({com.travelport.schema.common_v28_0.ObjectFactory.class, com.travelport.schema.system_v9_0.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SystemInfoPortType {

    @WebResult(name = "SystemInfoRsp", targetNamespace = "http://www.travelport.com/schema/system_v9_0", partName = "result")
    @WebMethod(action = "http://localhost:8080/kestrel/SystemService")
    public com.travelport.schema.system_v9_0.SystemInfoRsp service(
        @WebParam(partName = "parameters", name = "SystemInfoReq", targetNamespace = "http://www.travelport.com/schema/system_v9_0")
        com.travelport.schema.system_v9_0.SystemInfoReq parameters
    ) throws SystemFaultMessage;
}
