package com.travelport.service.universal_v38_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-09-13T11:38:38.470-06:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "UniversalRecordModifyService", 
                  wsdlLocation = "file:/C:/Travelport_1/SamplesAutoMation/AutoWork/travelport-uapi-tutorial-v38/Wsdl/universal_v38_0/UniversalRecord.wsdl",
                  targetNamespace = "http://www.travelport.com/service/universal_v38_0") 
public class UniversalRecordModifyService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.travelport.com/service/universal_v38_0", "UniversalRecordModifyService");
    public final static QName UniversalRecordModifyServicePort = new QName("http://www.travelport.com/service/universal_v38_0", "UniversalRecordModifyServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Travelport_1/SamplesAutoMation/AutoWork/travelport-uapi-tutorial-v38/Wsdl/universal_v38_0/UniversalRecord.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UniversalRecordModifyService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Travelport_1/SamplesAutoMation/AutoWork/travelport-uapi-tutorial-v38/Wsdl/universal_v38_0/UniversalRecord.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UniversalRecordModifyService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UniversalRecordModifyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UniversalRecordModifyService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UniversalRecordModifyService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UniversalRecordModifyService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UniversalRecordModifyService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns UniversalRecordModifyServicePortType
     */
    @WebEndpoint(name = "UniversalRecordModifyServicePort")
    public UniversalRecordModifyServicePortType getUniversalRecordModifyServicePort() {
        return super.getPort(UniversalRecordModifyServicePort, UniversalRecordModifyServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UniversalRecordModifyServicePortType
     */
    @WebEndpoint(name = "UniversalRecordModifyServicePort")
    public UniversalRecordModifyServicePortType getUniversalRecordModifyServicePort(WebServiceFeature... features) {
        return super.getPort(UniversalRecordModifyServicePort, UniversalRecordModifyServicePortType.class, features);
    }

}
