
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.travelport.service.universal_v38_0;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-09-13T11:38:38.049-06:00
 * Generated source version: 3.1.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "UniversalRecordModifyService",
                      portName = "UniversalRecordModifyServicePort",
                      targetNamespace = "http://www.travelport.com/service/universal_v38_0",
                      wsdlLocation = "file:/C:/Travelport_1/SamplesAutoMation/AutoWork/travelport-uapi-tutorial-v38/Wsdl/universal_v38_0/UniversalRecord.wsdl",
                      endpointInterface = "com.travelport.service.universal_v38_0.UniversalRecordModifyServicePortType")
                      
public class UniversalRecordModifyServicePortImpl implements UniversalRecordModifyServicePortType {

    private static final Logger LOG = Logger.getLogger(UniversalRecordModifyServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.travelport.service.universal_v38_0.UniversalRecordModifyServicePortType#service(com.travelport.schema.universal_v38_0.UniversalRecordModifyReq  parameters ,)com.travelport.soa.common.security.sessioncontext_v1.SessionContext  sessionContext ,)com.travelport.schema.universal_v38_0.SupportedVersions  supportedVersions )*
     */
    public com.travelport.schema.universal_v38_0.UniversalRecordModifyRsp service(com.travelport.schema.universal_v38_0.UniversalRecordModifyReq parameters,com.travelport.soa.common.security.sessioncontext_v1.SessionContext sessionContext,com.travelport.schema.universal_v38_0.SupportedVersions supportedVersions) throws AvailabilityFaultMessage , UniversalModifyFaultMessage , UniversalRecordFaultMessage    { 
        LOG.info("Executing operation service");
        System.out.println(parameters);
        System.out.println(sessionContext);
        System.out.println(supportedVersions);
        try {
            com.travelport.schema.universal_v38_0.UniversalRecordModifyRsp _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AvailabilityFaultMessage("AvailabilityFaultMessage...");
        //throw new UniversalModifyFaultMessage("UniversalModifyFaultMessage...");
        //throw new UniversalRecordFaultMessage("UniversalRecordFaultMessage...");
    }

}
