
package com.travelport.service.universal_v38_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-09-13T11:38:37.920-06:00
 * Generated source version: 3.1.5
 */

@WebFault(name = "UniversalRecordErrorInfo", targetNamespace = "http://www.travelport.com/schema/universal_v38_0")
public class UniversalRecordArchivedFaultMessage extends Exception {
    
    private com.travelport.schema.universal_v38_0.UniversalRecordErrorInfo universalRecordErrorInfo;

    public UniversalRecordArchivedFaultMessage() {
        super();
    }
    
    public UniversalRecordArchivedFaultMessage(String message) {
        super(message);
    }
    
    public UniversalRecordArchivedFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UniversalRecordArchivedFaultMessage(String message, com.travelport.schema.universal_v38_0.UniversalRecordErrorInfo universalRecordErrorInfo) {
        super(message);
        this.universalRecordErrorInfo = universalRecordErrorInfo;
    }

    public UniversalRecordArchivedFaultMessage(String message, com.travelport.schema.universal_v38_0.UniversalRecordErrorInfo universalRecordErrorInfo, Throwable cause) {
        super(message, cause);
        this.universalRecordErrorInfo = universalRecordErrorInfo;
    }

    public com.travelport.schema.universal_v38_0.UniversalRecordErrorInfo getFaultInfo() {
        return this.universalRecordErrorInfo;
    }
}
